apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: croffle
  name: croffle
spec:
  replicas: 1
  selector:
    matchLabels:
      app: croffle
  template:
    metadata:
      labels:
        app: croffle
    spec:
      containers:
        - image: osh1477/croffle-front:latest
          name: croffle
          resources: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: croffle
  name: croffle
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: croffle
  type: LoadBalancer
