apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: croffle-front
  name: croffle-front
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: croffle-front
  template:
    metadata:
      labels:
        app: croffle-front
    spec:
      containers:
        - image: osh1477/croffle-front:latest
          imagePullPolicy: Always
          name: croffle-front
          resources: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: croffle-front
  name: croffle-front
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: croffle-front
  type: LoadBalancer
